### ISSUE TITLE
millis() - 49 Days Timing Rollover.

### ISSUE THREAD

**Issue by yunjova** [marcelloromani/Arduino-SimpleTimer#7]
After 49 days of running, the millis() timer wraps and SimpleTimer will be broken (it will fire at wrong time).

The solution is to use "**unsigned** long" for **all** variables in the equation that checks the elapsed time against the wanted expiry time (if (current_millis - prev_millis[i] >= delays[i]) {).
So delays must also be unsigned long. See also: http://playground.arduino.cc/Code/TimingRollover.

**Comment by marcelloromani** [comment]
Thanks.

Fixed in https://github.com/marcelloromani/Arduino-SimpleTimer/commit/e6749cfc12343d8963b00e7d3348f74cf56b8066
